module.exports = [
    { 
        nome: "AEW WOMEN'S WORLD CHAMPIONSHIP",
        title: "AEW WOMEN'S WORLD CHAMPION",
        imgDynamite: "https://i.imgur.com/CMyvjJE.png",
        imgRaw: "https://i.imgur.com/eJV4KBw.png",
    },
    { 
        nome: "NXT WOMEN'S CHAMPIONSHIP",
        title: "NXT WOMEN'S CHAMPION",
        imgDynamite: "https://i.imgur.com/EXF6buq.png",
        imgRaw: "https://i.imgur.com/sN41TIp.png",
    },
    { 
        nome: "SMACKDOWN WOMEN'S CHAMPIONSHIP",
        title: "SMACKDOWN WOMEN'S CHAMPION",
        imgDynamite: "https://i.imgur.com/LcqiT53.png",
        imgRaw: "https://i.imgur.com/fsIERtP.png",
    },
    { 
        nome: "NXT UK WOMEN'S CHAMPIONSHIP",
        title: "NXT UK WOMEN'S CHAMPION",
        imgDynamite: "https://i.imgur.com/M9002KG.png",
        imgRaw: "https://i.imgur.com/5I86c6K.png",
    },
    { 
        nome: "WORLD OF STARDOM CHAMPIONSHIP",
        title: "WORLD OF STARDOM CHAMPION",
        imgDynamite: "https://i.imgur.com/fyh5Kvg.png",
        imgRaw: "https://i.imgur.com/byez2xI.png",
    },
    { 
        nome: "LADDER MATCH",
        title: "",
        imgDynamite: "https://i.imgur.com/us59F0w.png",
        imgRaw: "https://i.imgur.com/Q00XLCF.png",
    },
    { 
        nome: "EXPLODING BARBED WIRE MATCH",
        title: "",
        imgDynamite: "https://i.imgur.com/ypGIQGf.png",
        imgRaw: "https://i.imgur.com/ypGIQGf.png",
    },
    { 
        nome: "HAIR VS HAIR",
        title: "",
        imgDynamite: "https://i.imgur.com/ypGIQGf.png",
        imgRaw: "https://i.imgur.com/ypGIQGf.png",
    },
    { 
        nome: "STEEL CAGE MATCH",
        title: "",
        imgDynamite: "https://i.imgur.com/o02vkgj.png",
        imgRaw: "https://i.imgur.com/99d47S2.png",
    },
    { 
        nome: "STREET FIGHT",
        title: "",
        imgDynamite: "https://i.imgur.com/ypGIQGf.png",
        imgRaw: "https://i.imgur.com/ypGIQGf.png",
    },
    { 
        nome: "2 OUT OF 3 FALLS",
        title: "",
        imgDynamite: "https://i.imgur.com/ypGIQGf.png",
        imgRaw: "https://i.imgur.com/ypGIQGf.png",
    },
    { 
        nome: "LAST WOMAN STANDING",
        title: "",
        imgDynamite: "https://i.imgur.com/ypGIQGf.png",
        imgRaw: "https://i.imgur.com/ypGIQGf.png",
    },
    { 
        nome: "FALLS COUNT ANYWHERE",
        title: "",
        imgDynamite: "https://i.imgur.com/ypGIQGf.png",
        imgRaw: "https://i.imgur.com/ypGIQGf.png",
    },
    ]
