module.exports = [
    { 
        nome: "AEW WORLD CHAMPIONSHIP",
        title: "AEW WORLD CHAMPION",
        imgDynamite: "https://i.imgur.com/wNC4oZq.png",
        imgRaw: "https://i.imgur.com/duQfE9g.png",
    },
    { 
        nome: "WWE CHAMPIONSHIP",
        title: "WWE CHAMPION",
        imgDynamite: "https://i.imgur.com/wzvvxS6.png",
        imgRaw: "https://i.imgur.com/WTkFpqc.png",
    },
    { 
        nome: "TNT CHAMPIONSHIP",
        title: "TNT CHAMPION",
        imgDynamite: "https://i.imgur.com/teUDjO2.png",
        imgRaw: "https://i.imgur.com/7bK1Q5W.png",
    },
    { 
        nome: "UNIVERSAL CHAMPIONSHIP",
        title: "UNIVERSAL CHAMPION",
        imgDynamite: "https://i.imgur.com/PvbfRUG.png",
        imgRaw: "https://i.imgur.com/6fXjmM1.png",
    },
    { 
        nome: "AEW ALL-ATLANTIC CHAMPIONSHIP",
        title: "ALL-ATLANTIC CHAMPION",
        imgDynamite: "https://i.imgur.com/rf4MJmY.png",
        imgRaw: "https://i.imgur.com/cjtY7HN.png",
    },
    { 
        nome: "NXT NORTH AMERICAN CHAMPIONSHIP",
        title: "NORTH AMERICAN CHAMPION",
        imgDynamite: "https://i.imgur.com/Mips2MU.png",
        imgRaw: "https://i.imgur.com/LCmXFK2.png",
    },
    { 
        nome: "IMPACT! WORLD CHAMPIONSHIP",
        title: "IMPACT! WORLD CHAMPION",
        imgDynamite: "https://i.imgur.com/f6sYvIq.png",
        imgRaw: "https://i.imgur.com/9LohgrS.png",
    },
    { 
        nome: "IWGP WORLD HEAVYWEIGHT CHAMPIONSHIP",
        title: "IWGP WORLD HEAVYWEIGHT CHAMPION",
        imgDynamite: "https://i.imgur.com/nHMM5sR.png",
        imgRaw: "https://i.imgur.com/VLWz3eM.png",
    },
    { 
        nome: "LADDER MATCH",
        title: "",
        imgDynamite: "https://i.imgur.com/us59F0w.png",
        imgRaw: "https://i.imgur.com/Q00XLCF.png",
    },
    { 
        nome: "EXPLODING BARBED WIRE MATCH",
        title: "",
        imgDynamite: "https://i.imgur.com/ypGIQGf.png",
        imgRaw: "https://i.imgur.com/ypGIQGf.png",
    },
    { 
        nome: "HAIR VS HAIR",
        title: "",
        imgDynamite: "https://i.imgur.com/ypGIQGf.png",
        imgRaw: "https://i.imgur.com/ypGIQGf.png",
    },
    { 
        nome: "STEEL CAGE MATCH",
        title: "",
        imgDynamite: "https://i.imgur.com/o02vkgj.png",
        imgRaw: "https://i.imgur.com/99d47S2.png",
    },
    { 
        nome: "STREET FIGHT",
        title: "",
        imgDynamite: "https://i.imgur.com/ypGIQGf.png",
        imgRaw: "https://i.imgur.com/ypGIQGf.png",
    },
    { 
        nome: "2 OUT OF 3 FALLS",
        title: "",
        imgDynamite: "https://i.imgur.com/ypGIQGf.png",
        imgRaw: "https://i.imgur.com/ypGIQGf.png",
    },
    { 
        nome: "LAST MAN STANDING",
        title: "",
        imgDynamite: "https://i.imgur.com/ypGIQGf.png",
        imgRaw: "https://i.imgur.com/ypGIQGf.png",
    },
    { 
        nome: "FALLS COUNT ANYWHERE",
        title: "",
        imgDynamite: "https://i.imgur.com/ypGIQGf.png",
        imgRaw: "https://i.imgur.com/ypGIQGf.png",
    },
    { 
        nome: "DPW NATIONAL CHAMPIONSHIP",
        title: "DPW NATIONAL CHAMPION",
        imgDynamite: "https://i.imgur.com/6DQjqRI.png",
        imgRaw: "https://i.imgur.com/1p9k98d.png",
    },
    ]
